25 leen status aanpassen
ACI-Rental/backend pull request #34
Opened 2021-06-07 11:55 UTC by Pigna

2021-06-07 12:42 UTC, SieBrum requested changes

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                        //Verwijderen reservering? pickup return date zelfde data?
todo?

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                return BadRequest("RESERVATION.ACTION.INVALIDCALL");
Deze vertaling bestaat niet in de front-end

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                return BadRequest("RESERVATION.ACTION.INVALID.ID");
Deze vertaling bestaat niet in de front-end volgensmij

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                        return BadRequest("RESERVATION.ACTION.INVALID.ACTION");
Deze vertaling bestaat niet in de front-end volgensmij

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                return NotFound("RESERVATION.ACTION.NOT_FOUND");
Deze vertaling bestaat niet in de front-end volgensmij

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                return BadRequest("RESERVATION.ACTION.INVALID.ID");
Deze vertaling bestaat niet in de front-end volgensmij

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Models/Reservation.cs
> +        ///
///

2021-06-07 12:42 UTC, SieBrum commented on ReservationService/Models/DTO/ReservationActionModel.cs
> +        /// Action that is done to the reservation
Misschien kan je hier beter een ENUM van maken

2021-06-07 14:51 UTC, Pigna commented on ReservationService/Controllers/ReservationController.cs
> +                        //Verwijderen reservering? pickup return date zelfde data?
Valt buiten de scope van de ticket, heb er todo van gemaakt.

2021-06-07 17:30 UTC, SieBrum requested changes

2021-06-07 17:30 UTC, SieBrum commented on ReservationService/Controllers/ReservationController.cs
> +                        //TODO: Delete reservation
Ik zou hier misschien een NotImplementedException throwen als je deze (nog) niet van plan bent om te bouwen

2021-06-08 08:18 UTC, SieBrum approved these changes

2021-06-08 08:18 UTC, SieBrum commented
LGTM

2021-06-08 08:18 UTC, merged