Feature/OIDC keycloak
ACI-Rental/backend pull request #85
Opened 2022-04-19 11:31 UTC by rachied

Implement external login through SURFconext by using Keycloak as an identity broker

2022-04-19 11:32 UTC, Noodleyy commented
![image](https://user-images.githubusercontent.com/40075712/163994272-e7d4f6c5-e71f-453d-bd59-0e992ad29ca7.png)

2022-04-19 12:41 UTC, Noodleyy requested changes

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products.Test.Integration/Fixtures/ProductAppFactory.cs
> +            // serviceCollection.AddAuthentication(TestAuthHandler.AuthenticationScheme)
Waarom deze gecommenteerde stuff?

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Data/Repositories/NoteRepository.cs
> +    }
Add whitespace for my slightly dumb brain

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Domain/Category/CategoryService.cs
> +        return CategoryResponse.MapFromModel(result);
I'd like a whitespace :)

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Domain/Category/CategoryService.cs
> +        return model.Map(CategoryResponse.MapFromModel);
Maybe one more whitespace

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Domain/Category/CategoryService.cs
> +        return models.Select(CategoryResponse.MapFromModel).ToList();
Pls whitespace for my brain

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Domain/Note/NoteService.cs
> +        return NoteResponse.MapFromModel(result);
Insert Whitespace pls

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Domain/Product/ProductService.cs
>          return result.Map(ProductResponse.From);
White space under line 21 pls

2022-04-19 12:41 UTC, Noodleyy commented on ACI.Products/Program.cs
> +    });
Naar gateway at some point but ok :)

2022-04-19 12:50 UTC, Noodleyy requested changes

2022-04-19 12:50 UTC, Noodleyy commented on OcelotAPIGateway/ocelot.json
>    "GlobalConfiguration": {
Discard changes, want mijn branch heeft de 'juiste routes'

2022-04-19 12:50 UTC, Noodleyy commented on OcelotAPIGateway/ocelot.Development.json
>  {
Discard changes, want mijn branch heeft de 'juiste routes'

2022-04-20 15:12 UTC, rachied commented on ACI.Products.Test.Integration/Fixtures/ProductAppFactory.cs
> +            // serviceCollection.AddAuthentication(TestAuthHandler.AuthenticationScheme)
Overblijfsel van debuggen - zal ik weghalen

2022-04-25 11:44 UTC, merged